#!/bin/sh
#
# fluxbox startup-script:
#
# Lines starting with a '#' are ignored.

# Change your keymap:
xmodmap "/home/bulkan/.Xmodmap"

# Applications you want to run with fluxbox.
# MAKE SURE THAT APPS THAT KEEP RUNNING HAVE AN ''&'' AT THE END.
#
# unclutter -idle 2 &
# wmnd &
# wmsmixer -w &
# idesk &

# And last but not least we start fluxbox.
# Because it is the last app you have to run it with ''exec'' before it.

cairo-dock &
#bbpager &
gnome-sound-applet &
nm-applet &
fbsetbg /home/bulkan/Pictures/lines.jpg &
#wmcpuload &
#wmmemload &
wmbattery &
wmwave &
dropbox start &
/usr/bin/terminator -e byobu &
conky &


exec fluxbox
# or if you want to keep a log:
 #exec fluxbox -log "/home/bulkan/.fluxbox/log"
