[java]
disabled = true

[kubernetes]
format = '[$context \($namespace\)](dimmed green) '
detect_folders = ["kubernetes"]
disabled = false

[docker_context]
disabled = true

[aws]
disabled = true

[nodejs]
disabled = true

[gcloud]
disabled = true

[rust]
disabled = true

[python]
disabled = true

[git_status]
disabled = true
