[java]
disabled = true

[kubernetes]
format = '[$context \($namespace\)](dimmed green) '
detect_folders = ["kubernetes"]

[docker_context]
disabled = true

[aws]
disabled = true

[nodejs]
disabled = true

[gcloud]
disabled = true

[rust]
disabled = false
