export PATH=/usr/local/bin:$PATH:$HOME/.bin

export NODE_PATH=/usr/local/lib/node_modules/

alias mvim="mvim --remote-tab"
alias redis-server="redis-server /usr/local/etc/redis.conf"
alias ls="ls -G"
alias grep='grep --color=auto'
alias fgrep='fgrep --color=auto'
alias egrep='egrep --color=auto'
alias ll='ls -alF'
alias la='ls -A'
alias l='ls -CF'


# from @tjholowaychuck
alias ga="git add"
alias gbd="git branch -D"
alias gst="git status"
alias gc="git commit"
alias gca="git commit -a"
alias gm="git merge --no-ff"
alias gpt="git push --tags"
alias gp="git push"
#alias grh="git reset --hard"
alias gb="git branch"
alias gcob="git checkout -b"
alias gco="git checkout"
alias gba="git branch -a"
alias gcp="git cherry-pick"
alias gl="git log --pretty='format:%Cgreen%h%Creset %an - %s' --graph"
alias gpom="git pull origin master"
alias gcd='cd "`git rev-parse --show-toplevel`"'


export WORKON_HOME=$HOME/src/python
export PROJECT_HOME=$HOME/src/python
export VIRTUALENVWRAPPER_SCRIPT=/usr/local/bin/virtualenvwrapper.sh


export GOPATH=$HOME/src/go
export PATH=$PATH:$GOPATH/bin

source /usr/local/bin/virtualenvwrapper.sh


function _venv() {
    if [[ $VIRTUAL_ENV != "" ]] 
        then
      # Strip out the path and just leave the env name
      echo "(${VIRTUAL_ENV##*/})"
    else
      # In case you don't have one activated
      echo ""
    fi
}

function parse_git_branch {
    ref=$(git symbolic-ref HEAD 2> /dev/null) || return
    echo "["${ref#refs/heads/}"] "
}


#export PROMPT_COMMAND='PS1="$(_venv)[\w\[\033[00m\]]$(parse_git_branch): "'

export PROMPT_COMMAND='PS1=" $(_venv) \[\e[0;33m\]\w \[\e[1;34m\]\$(parse_git_branch)\[\e[0m\]∫ "'
